# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3miDHkJVcDU7vqnA74Y5C7EZIKWYFKZ
"""

import re
from typing import List, Optional
import streamlit as st
import reparto_express as rx

def _require_plotly():
    try:
        import plotly.graph_objects as go
        return go
    except ModuleNotFoundError:
        st.error("No se pudo importar 'plotly'. Asegúrate de agregarlo a requirements.txt.")
        st.stop()

def parse_tokens(s: str) -> List[str]:
    return [t.strip().upper() for t in re.split(r"[\s,]+", s.strip()) if t.strip()]

def plot_points_route(points, order: Optional[List[str]] = None, title: str = ""):
    go = _require_plotly()
    xs = [p[0] for p in points.values()]
    ys = [p[1] for p in points.values()]
    fig = go.Figure()

    fig.add_trace(go.Scatter(x=xs, y=ys, mode="markers+text", text=list(points.keys()),
                             textposition="top center", marker=dict(size=12, color="#ffcc00"), name="Entregas"))
    fig.add_trace(go.Scatter(x=[rx.ALMACEN[0]], y=[rx.ALMACEN[1]], mode="markers+text",
                             text=["H"], textposition="top center", marker=dict(size=14, color="#ff3355"), name="Almacén"))

    if order:
        route_x = [rx.ALMACEN[0]] + [points[n][0] for n in order] + [rx.ALMACEN[0]]
        route_y = [rx.ALMACEN[1]] + [points[n][1] for n in order] + [rx.ALMACEN[1]]
        fig.add_trace(go.Scatter(x=route_x, y=route_y, mode="lines+markers", line=dict(width=3, color="#00d1ff"), name="Ruta"))

    fig.update_layout(title=title, template="plotly_dark", height=650, margin=dict(l=20, r=20, t=50, b=20))
    return fig

def plot_graph(points, edges, path: Optional[List[str]], title: str = ""):
    go = _require_plotly()
    fig = go.Figure()

    for key, w in edges.items():
        a, b = tuple(key)
        fig.add_trace(go.Scatter(x=[points[a][0], points[b][0]], y=[points[a][1], points[b][1]],
                                 mode="lines", line=dict(color="rgba(200,200,200,0.25)", width=2), showlegend=False))

    if path and len(path) >= 2:
        for u, v in zip(path, path[1:]):
            fig.add_trace(go.Scatter(x=[points[u][0], points[v][0]], y=[points[u][1], points[v][1]],
                                     mode="lines", line=dict(color="#00d1ff", width=4), showlegend=False))

    fig.add_trace(go.Scatter(x=[p[0] for p in points.values()], y=[p[1] for p in points.values()],
                             mode="markers+text", text=list(points.keys()), textposition="top center",
                             marker=dict(size=12, color="#ffcc00"), showlegend=False))

    fig.update_layout(title=title, template="plotly_dark", height=650, margin=dict(l=20, r=20, t=50, b=20))
    return fig

st.set_page_config(page_title="Reparto Express", layout="wide")
st.title("Reparto Express — App (Streamlit)")
st.caption("Selecciona misión + estrellas, genera el escenario y evalúa tu jugada.")

instrucciones = {
    1: "🎯 **Misión 1 (TSP):** Visita todos los puntos listados exactamente una vez y regresa al almacén (H) recorriendo la menor distancia posible. Escribe el orden separado por espacios (Ej: A C B D).",
    2: "🎯 **Misión 2 (CVRP):** Tienes un límite de carga. Escribe un viaje por línea (Ej: A C en la línea 1, B D en la línea 2) asegurándote de no exceder la capacidad total por ruta.",
    3: "🎯 **Misión 3 (VRPTW):** Cada punto tiene una ventana de tiempo [inicio, fin]. Ordena tu ruta para minimizar llegar tarde. (Ej: A B C D).",
    4: "🎯 **Misión 4 (Knapsack):** No puedes llevar todo. Selecciona los ítems que maximicen el valor total sin sobrepasar el peso permitido de la mochila. (Ej: A D F).",
    5: "🎯 **Misión 5 (Dijkstra):** Encuentra la ruta más corta conectando nodos desde el punto de Origen hasta el Destino. (Ej: A B D F).",
    6: "🎯 **Misión 6 (Flota):** Divide las entregas entre tus vehículos (una línea de texto por vehículo) intentando que el vehículo que más tarde, termine lo antes posible (minimizar el makespan).",
    7: "🎯 **Misión 7 (Orienteering):** Tienes un presupuesto de kilómetros. Elige qué puntos visitar (en orden) para recolectar el mayor premio sin exceder los kilómetros dados."
}

with st.sidebar:
    mission = st.selectbox("Misión", options=[(1, "TSP"), (2, "CVRP"), (3, "VRPTW"), (4, "Knapsack"), (5, "Dijkstra"), (6, "Flota"), (7, "Orienteering")], format_func=lambda x: f"{x[0]} — {x[1]}")[0]
    stars = st.slider("Dificultad (estrellas)", 1, 5, 3, 1)
    seed = st.number_input("Seed (reproducible)", value=1, step=1)
    generate = st.button("Generar escenario", type="primary")

if "scenario" not in st.session_state:
    st.session_state.scenario = None

if generate or st.session_state.scenario is None:
    if mission == 1: sc = rx.preparar_tsp(int(seed), int(stars)); st.session_state.meta = {"type": "points", "points": sc["entregas"], "tam": sc["tam"]}
    elif mission == 2: sc = rx.preparar_cvrp(int(seed), int(stars)); st.session_state.meta = {"type": "points", "points": sc["entregas"], "tam": sc["tam"]}
    elif mission == 3: sc = rx.preparar_vrptw(int(seed), int(stars)); st.session_state.meta = {"type": "points", "points": sc["entregas"], "tam": sc["tam"]}
    elif mission == 4: sc = rx.preparar_mochila(int(seed), int(stars)); st.session_state.meta = {"type": "knapsack"}
    elif mission == 5: sc = rx.preparar_dijkstra(int(seed), int(stars)); st.session_state.meta = {"type": "graph"}
    elif mission == 6: sc = rx.preparar_flota(int(seed), int(stars)); st.session_state.meta = {"type": "points", "points": sc["entregas"], "tam": sc["tam"]}
    elif mission == 7: sc = rx.preparar_orienteering(int(seed), int(stars)); st.session_state.meta = {"type": "points", "points": sc["entregas"], "tam": sc["tam"]}
    st.session_state.scenario = sc

scenario = st.session_state.scenario
meta = st.session_state.meta

st.info(instrucciones[mission])

col_left, col_right = st.columns([1.15, 0.85])

with col_left:
    if meta["type"] == "points":
        st.plotly_chart(plot_points_route(meta["points"], None, title=f"Misión {mission} — {'★'*stars}"), use_container_width=True)
        st.write("**Puntos:**", {k: v for k, v in meta["points"].items()})
    elif meta["type"] == "graph":
        st.write(f"Origen: **{scenario['origen']}** | Destino: **{scenario['destino']}**")
        st.plotly_chart(plot_graph(scenario["puntos"], scenario["aristas"], None, title=f"Misión 5 — {'★'*stars}"), use_container_width=True)
    elif meta["type"] == "knapsack":
        st.write(f"Capacidad: **{scenario['capacidad']}**")
        st.table([{"Item": k, "Valor": v[0], "Peso": v[1]} for k, v in scenario["items"].items()])

with col_right:
    st.subheader("Tu jugada")

    if mission in (1, 3):
        inp = st.text_input("Ingresa tu orden", value="")
        if st.button("Evaluar"):
            order = parse_tokens(inp)
            puntos = scenario["entregas"]
            if set(order) != set(puntos.keys()) or len(order) != len(puntos):
                st.error("Orden inválido: debes usar cada punto exactamente una vez.")
            else:
                if mission == 1:
                    d = rx.longitud_ruta(order, puntos)
                    score = rx.puntuar_min(d, rx.longitud_ruta(rx.ruta_vecino_mas_cercano(puntos), puntos))
                    st.metric("Puntuación", f"{score}/100")
                    st.plotly_chart(plot_points_route(puntos, order, title=f"Tu ruta — {score}/100"), use_container_width=True)
                else:
                    dist, tard, _ = rx._sim_vrptw(order, puntos, scenario["ventanas"], scenario["velocidad"])
                    costo = dist + scenario["pen"] * tard
                    edd = sorted(puntos.keys(), key=lambda k: scenario["ventanas"][k][1])
                    distb, tardb, _ = rx._sim_vrptw(edd, puntos, scenario["ventanas"], scenario["velocidad"])
                    score = rx.puntuar_min(costo, distb + scenario["pen"] * tardb)
                    st.metric("Puntuación", f"{score}/100")
                    st.plotly_chart(plot_points_route(puntos, order, title=f"Tu ruta — {score}/100"), use_container_width=True)

    elif mission == 2:
        text = st.text_area("Ingresa tus viajes (una línea por vehículo)", value="")
        if st.button("Evaluar"):
            viajes = [parse_tokens(ln) for ln in text.splitlines() if ln.strip()]
            all_nodes = [n for v in viajes for n in v]
            puntos = scenario["entregas"]
            if len(all_nodes) != len(set(all_nodes)) or set(all_nodes) != set(puntos.keys()):
                st.error("Revisa tus datos: incluye todas las entregas una vez sin repetir.")
            else:
                cap, dem = scenario["capacidad"], scenario["demanda"]
                if any(sum(dem[n] for n in v) > cap for v in viajes):
                    st.error("Excediste la capacidad en uno de los viajes.")
                else:
                    dist = sum(rx.longitud_ruta(v, puntos) for v in viajes)
                    base = sum(rx.longitud_ruta(v, puntos) for v in rx._heuristica_cvrp(puntos, dem, cap))
                    st.metric("Puntuación", f"{rx.puntuar_min(dist, base)}/100")

    elif mission == 4:
        inp = st.text_input("Selección de Ítems", value="")
        if st.button("Evaluar"):
            sel = parse_tokens(inp)
            if not set(sel) <= set(scenario["items"].keys()):
                st.error("Ítems inválidos.")
            else:
                peso = sum(scenario["items"][k][1] for k in sel)
                if peso > scenario["capacidad"]:
                    st.error("Sobrepeso: puntuación 0.")
                else:
                    valor = sum(scenario["items"][k][0] for k in sel)
                    opt, _ = rx.knapsack_optimo(scenario["items"], scenario["capacidad"])
                    st.metric("Puntuación", f"{rx.puntuar_max(valor, opt)}/100")

    elif mission == 5:
        inp = st.text_input("Camino", value="")
        if st.button("Evaluar"):
            path = parse_tokens(inp)
            if not path or path[0] != scenario["origen"] or path[-1] != scenario["destino"]:
                st.error("Camino inválido (origen/destino).")
            else:
                try:
                    cost = sum(dict(scenario["grafo"][u])[v] for u, v in zip(path, path[1:]))
                    opt_cost, _ = rx.dijkstra(scenario["grafo"], scenario["origen"], scenario["destino"])
                    score = rx.puntuar_min(cost, opt_cost)
                    st.metric("Puntuación", f"{score}/100")
                    st.plotly_chart(plot_graph(scenario["puntos"], scenario["aristas"], path, title=f"Tu camino — {score}/100"), use_container_width=True)
                except KeyError:
                    st.error("Una de las aristas ingresadas no existe.")

    elif mission == 6:
        text = st.text_area("Vehículos", value="")
        if st.button("Evaluar"):
            grupos = [parse_tokens(ln) for ln in text.splitlines() if ln.strip()]
            puntos, k = scenario["entregas"], scenario["k"]
            if len(grupos) != k:
                st.error(f"Debes ingresar exactamente {k} líneas.")
            else:
                all_nodes = [n for g in grupos for n in g]
                if set(all_nodes) != set(puntos.keys()):
                    st.error("Asigna cada entrega exactamente una vez.")
                else:
                    makes = max(rx._largos_grupos(grupos, puntos))
                    makesb = max(rx._largos_grupos(rx._heuristica_flota(puntos, k), puntos))
                    st.metric("Puntuación", f"{rx.puntuar_min(makes, makesb)}/100")

    elif mission == 7:
        inp = st.text_input("Orden de Puntos", value="")
        if st.button("Evaluar"):
            order = parse_tokens(inp)
            puntos = scenario["entregas"]
            if not set(order) <= set(puntos.keys()):
                st.error("Puntos inválidos.")
            else:
                dist = rx.longitud_ruta(order, puntos) if order else 0.0
                if dist > scenario["presupuesto"] + 1e-9:
                    st.error("Te pasaste del presupuesto: puntuación 0.")
                else:
                    val = sum(scenario["premio"][k] for k in order)
                    opt_val, _, _ = rx._orienteering_optimo(puntos, scenario["premio"], scenario["presupuesto"], int(stars))
                    score = rx.puntuar_max(val, opt_val)
                    st.metric("Puntuación", f"{score}/100")
                    st.plotly_chart(plot_points_route(puntos, order, title=f"Tu ruta — {score}/100"), use_container_width=True)
